'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, Check, CreditCard, LockKeyhole } from 'lucide-react';
import Link from 'next/link';

type Item = { name: string; price: number; quantity: number; image: string };

export function CheckoutForm() {
  const [items, setItems] = useState<Item[]>([]);
  const [paid, setPaid] = useState(false);
  const [busy, setBusy] = useState(false);
  const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0);
  useEffect(() => { const saved = window.localStorage.getItem('kl-cart'); if (saved) setItems(JSON.parse(saved) as Item[]); }, []);
  async function pay(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); await new Promise(resolve => setTimeout(resolve, 800)); window.localStorage.removeItem('kl-cart'); setBusy(false); setPaid(true); }
  if (paid) return <div className="animate-pop mx-auto max-w-xl rounded-3xl bg-[#1d392c] p-10 text-center text-[#f3eee4]"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#d5a84b] text-[#13241d]"><Check /></div><h1 className="mt-6 font-display text-5xl">Your chai is on its way.</h1><p className="mt-4 leading-7 text-[#c4d4c7]">This development checkout is simulated safely. Connect Razorpay keys before accepting real payments.</p><Link href="/shop" className="mt-8 inline-block rounded-full bg-[#d5a84b] px-6 py-3 font-bold text-[#13241d]">Back to shop</Link></div>;
  return <div className="grid gap-8 lg:grid-cols-[1fr_.75fr]"><form onSubmit={pay} className="rounded-3xl border border-[#d8cbb5] bg-[#fffaf0] p-7 shadow-[0_18px_50px_rgba(65,46,24,.08)]"><div className="flex items-center gap-3"><LockKeyhole className="text-[#8b4f2f]" size={20} /><h2 className="font-display text-3xl text-[#1d392c]">Delivery details</h2></div><div className="mt-7 grid gap-4 md:grid-cols-2"><input required className="rounded-xl border border-[#cdbfa7] bg-white/70 px-4 py-4 outline-none focus:border-[#8b4f2f]" placeholder="Full name" /><input required type="tel" className="rounded-xl border border-[#cdbfa7] bg-white/70 px-4 py-4 outline-none focus:border-[#8b4f2f]" placeholder="Phone number" /><input required type="email" className="rounded-xl border border-[#cdbfa7] bg-white/70 px-4 py-4 outline-none focus:border-[#8b4f2f] md:col-span-2" placeholder="Email address" /><textarea required className="min-h-28 rounded-xl border border-[#cdbfa7] bg-white/70 px-4 py-4 outline-none focus:border-[#8b4f2f] md:col-span-2" placeholder="Delivery address" /><input required className="rounded-xl border border-[#cdbfa7] bg-white/70 px-4 py-4 outline-none focus:border-[#8b4f2f]" placeholder="City" /><input required className="rounded-xl border border-[#cdbfa7] bg-white/70 px-4 py-4 outline-none focus:border-[#8b4f2f]" placeholder="Pincode" /></div><button disabled={busy || items.length === 0} type="submit" className="mt-7 w-full rounded-xl bg-[#8b4f2f] py-4 font-bold text-white hover:bg-[#6f3d27] disabled:cursor-not-allowed disabled:opacity-50"><CreditCard className="mr-2 inline" size={18} />{busy ? 'Opening secure payment…' : 'Pay securely · ₹' + total}</button><p className="mt-3 text-center text-xs text-[#829282]">Development mode · no money will be charged</p></form><aside className="h-fit rounded-3xl bg-[#1d392c] p-7 text-[#f3eee4]"><h2 className="font-display text-3xl">Your order</h2>{items.length === 0 ? <p className="mt-6 text-[#c4d4c7]">Your cart is empty. <Link href="/shop" className="text-[#d5a84b] underline">Browse tea</Link></p> : <div className="mt-6 space-y-5">{items.map(item => <div key={item.name} className="flex justify-between border-b border-white/10 pb-4 text-sm"><span>{item.name} × {item.quantity}</span><span>₹{item.price * item.quantity}</span></div>)}<div className="flex justify-between pt-2 text-lg font-bold"><span>Total</span><span>₹{total}</span></div></div>}<Link href="/shop" className="mt-8 inline-flex items-center text-sm text-[#d5a84b]"><ArrowLeft className="mr-2" size={15} /> Back to shop</Link></aside></div>;
}
