import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, Leaf } from 'lucide-react';

const lots = [
  ['PD-2847', 'Primary Dust', '3.2 MT', 'Assam', '7.2%', '₹168–182/kg'],
  ['CD-2911', 'Coarse Dust', '1.8 MT', 'Dooars', '7.8%', '₹145–158/kg'],
  ['GW-1174', 'Green Tea Waste', '5.0 MT', 'Nilgiris', '6.9%', '₹62–74/kg'],
  ['TD-3182', 'Tea Dust', '850 kg', 'Siliguri', '7.5%', '₹118–132/kg'],
];

export default function LotsPage() { return <main className="min-h-screen bg-[#f3eee4] text-[#24322c]"><header className="border-b border-[#24322c]/10 bg-[#13241d] px-6 py-5 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="flex items-center gap-2 font-display text-2xl"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#d5a84b] text-[#13241d]"><Leaf size={18} /></span>Kettle<span className="text-[#d5a84b]">&</span>Leaf</Link><Link href="/" className="text-sm text-[#c4d4c7]"><ArrowLeft className="mr-2 inline" size={15} /> Back home</Link></div></header><div className="mx-auto max-w-7xl px-6 py-16"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#63816a]">Warehouse window · verified stock</p><h1 className="mt-4 max-w-3xl font-display text-6xl leading-none text-[#1d392c]">Lots you can actually inspect.</h1><p className="mt-6 max-w-xl leading-7 text-[#617263]">Every listing is a physical lot with a number, origin and current available weight. Request a quote and we will share the full spec sheet.</p><div className="mt-12 flex flex-wrap gap-2"><button className="rounded-full bg-[#1d392c] px-5 py-2 text-sm font-bold text-white">All grades</button><button className="rounded-full border border-[#24322c]/15 px-5 py-2 text-sm">PD</button><button className="rounded-full border border-[#24322c]/15 px-5 py-2 text-sm">CD</button><button className="rounded-full border border-[#24322c]/15 px-5 py-2 text-sm">Green waste</button></div><div className="mt-8 grid gap-5 md:grid-cols-2">{lots.map(lot => <article key={lot[0]} className="rounded-2xl border border-[#24322c]/10 bg-white/60 p-7"><div className="flex justify-between"><span className="rounded-full bg-[#dfe8df] px-3 py-1 text-xs font-bold text-[#365840]">{lot[1]}</span><span className="text-xs text-[#829282]">{lot[0]}</span></div><div className="mt-10 flex items-end justify-between"><div><p className="font-display text-5xl text-[#1d392c]">{lot[2]}</p><p className="mt-2 text-sm text-[#617263]">available · {lot[3]}</p></div><p className="text-right text-sm font-bold text-[#8f6828]">{lot[5]}<span className="block text-xs font-normal text-[#829282]">indicative</span></p></div><div className="mt-8 grid grid-cols-2 border-t border-[#24322c]/10 pt-4 text-sm"><span><small className="block text-[#829282]">Moisture</small>{lot[4]}</span><span><small className="block text-[#829282]">Status</small><span className="text-[#48724f]">Available now</span></span></div><Link href="/#enquiry" className="mt-7 block rounded-xl bg-[#1d392c] py-3 text-center text-sm font-bold text-white">Enquire for this lot <ArrowUpRight className="ml-1 inline" size={15} /></Link></article>)}</div></div></main> }
